SYSTEM_ADMIN = 'SYSTEM_ADMIN'
COMPANY_ADMIN = 'COMPANY_ADMIN'
COMPANY_STATUSES = ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')
CARD_REQUEST_STATUSES = ('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'COMPLETED', 'FAILED')
