'use client';
import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import StatusBadge from './StatusBadge';
import CardPreview from './CardPreview';
import ReviewDialog from './ReviewDialog';

const date = value => new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
export default function AdminDashboard() {
  const [data, setData] = useState({ companies: [], requests: [], templates: [] });
  const [tab, setTab] = useState('companies');
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('ALL');
  const [review, setReview] = useState(null);
  const [reason, setReason] = useState('');
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  async function load() {
    try { const [companies, requests, templates] = await Promise.all([api('/admin/companies'), api('/admin/card-requests'), api('/admin/templates')]); setData({ companies, requests, templates }); }
    catch (e) { setError(e.message); } finally { setLoading(false); }
  }
  useEffect(() => { load(); }, []);
  async function mutate(path, body) {
    setBusy(true); setError(''); setMessage('');
    try { await api(path, { method: 'PATCH', body: JSON.stringify(body) }); setReview(null); setMessage('Your decision has been saved.'); await load(); }
    catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  function open(item) { setReview({ ...item, kind: tab }); setReason(''); setError(''); }
  const pending = data.companies.filter(c => c.status === 'PENDING').length;
  const pendingRequests = data.requests.filter(r => r.status === 'PENDING').length;
  const visible = data[tab].filter(item => (status === 'ALL' || item.status === status) && JSON.stringify([item.name, item.company?.name, item.created_by?.username, item.admins?.map(a => a.email), item.id]).toLowerCase().includes(search.toLowerCase()));
  return <>
    <div className="stats-grid">{[['Registered companies', data.companies.length, `${pending} awaiting review`], ['Pending card requests', pendingRequests, 'Ready for your decision'], ['Completed requests', data.requests.filter(r => r.status === 'COMPLETED').length, 'Cards ready to share'], ['Active templates', data.templates.filter(t => t.is_active).length, 'One consistent identity']].map(([label, count, note], i) => <div className="stat-card" key={label}><div className="flex justify-between text-xs text-slate-500">{label}<span className="text-indigo-500">{['◈', '▤', '✓', '▦'][i]}</span></div><p className="mt-4 text-3xl font-semibold tracking-tight">{count}</p><p className="mt-2 text-xs text-slate-400">{note}</p></div>)}</div>
    <div className="mt-7 flex flex-wrap items-center justify-between gap-4"><div className="tabs">{[['companies', 'Companies'], ['requests', 'Card requests'], ['templates', 'Templates']].map(([key, label]) => <button key={key} className={tab === key ? 'tab active' : 'tab'} onClick={() => { setTab(key); setSearch(''); setStatus('ALL'); }}>{label}<span>{data[key].length}</span></button>)}</div><button className="btn-quiet" disabled={busy} onClick={load}>↻ Refresh</button></div>
    {message && <p role="status" className="notice-success mt-5">{message}</p>}{error && !review && <p role="alert" className="notice-error mt-5">{error}</p>}
    <section className="panel mt-5"><div className="panel-header"><div><h2 className="font-semibold">{tab === 'companies' ? 'Company directory' : tab === 'requests' ? 'Review queue' : 'Your card collection'}</h2><p className="mt-1 text-xs text-slate-500">{tab === 'templates' ? 'Curated layouts for a memorable first impression.' : 'Open a review to see who submitted it and check the details.'}</p></div>{tab !== 'templates' && <div className="flex flex-wrap gap-2"><input aria-label="Search records" className="input compact" placeholder="Search name, email or ID…" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Filter status" className="input compact" value={status} onChange={e => setStatus(e.target.value)}>{['ALL', 'PENDING', 'APPROVED', 'REJECTED', ...(tab === 'companies' ? ['SUSPENDED'] : ['COMPLETED', 'PROCESSING', 'FAILED'])].map(s => <option key={s}>{s}</option>)}</select></div>}</div>
    {loading ? <p role="status" className="empty-state">Loading your workspace…</p> : tab === 'templates' ? <div className="grid gap-5 p-6 md:grid-cols-2 xl:grid-cols-3">{data.templates.map(t => <article key={t.id}><CardPreview style={t.style_key} /><div className="mt-5 flex justify-between"><h3 className="font-semibold">{t.name}</h3><span className="text-xs text-slate-500">{t.is_active ? 'Active' : 'Inactive'}</span></div><p className="mt-2 text-sm text-slate-500">{t.description}</p><button className="btn-secondary mt-4 w-full" disabled={busy} onClick={() => mutate(`/admin/templates/${t.id}`, { is_active: !t.is_active })}>{t.is_active ? 'Deactivate template' : 'Activate template'}</button></article>)}</div> : <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>{tab === 'companies' ? 'Company' : 'Request / company'}</th><th>Submitted by</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map(item => { const owner = tab === 'companies' ? item.admins?.[0] : item.created_by; return <tr key={item.id}><td><p className="font-semibold">{tab === 'companies' ? item.name : item.company?.name}</p><p className="mt-1 text-xs text-slate-400">{tab === 'companies' ? `Company #${item.id}` : `Request #${item.id} · ${item.items.length} cards`}</p></td><td><p>{owner?.username || 'Not available'}</p><p className="mt-1 text-xs text-slate-400">{owner?.email}</p></td><td className="text-slate-500">{date(item.created_at)}</td><td><StatusBadge value={item.status} /></td><td><button className="btn-secondary" onClick={() => open(item)}>Review details ↗</button></td></tr>; })}</tbody></table>{!visible.length && <div className="empty-state"><p className="text-lg font-semibold text-slate-700">Nothing here just yet.</p><p className="mt-2">New submissions will appear here. Try another filter or refresh.</p></div>}</div>}</section>
    {review && <ReviewDialog title={review.kind === 'companies' ? review.name : `Card request #${review.id}`} onClose={() => setReview(null)} busy={busy}>
      <StatusBadge value={review.status} /><dl className="review-grid"><div><dt>Company</dt><dd>{review.name || review.company?.name}</dd></div><div><dt>Submitted</dt><dd>{date(review.created_at)}</dd></div>{(review.kind === 'companies' ? review.admins || [] : [review.created_by]).filter(Boolean).map(owner => <div key={owner.id}><dt>{review.kind === 'companies' ? 'Company administrator' : 'Requested by'}</dt><dd>{owner.username}<span className="mt-1 block text-sm font-normal text-slate-500">{owner.email}</span></dd></div>)}</dl>
      {review.kind === 'requests' && <><h3 className="mb-3 font-semibold">Selected template · {review.template?.name}</h3><div className="max-w-sm"><CardPreview style={review.template?.style_key} company={review.company?.name} name={review.items[0]?.employee?.name} designation={review.items[0]?.employee?.designation} /></div><p className="mt-2 text-xs text-slate-400">Style preview. Generated PDFs use each employee’s saved details.</p><h3 className="mt-6 mb-2 font-semibold">Employees included ({review.items.length})</h3><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Employee</th><th>Designation / department</th><th>Contact</th></tr></thead><tbody>{review.items.map(i => <tr key={i.id}><td>{i.employee.name}<p className="text-xs text-slate-400">{i.employee.employee_id}</p></td><td>{i.employee.designation}<p className="text-xs text-slate-400">{i.employee.department}</p></td><td>{i.employee.email}<p className="text-xs text-slate-400">{i.employee.phone}</p></td></tr>)}</tbody></table></div></>}
      {review.rejection_reason && <p className="notice-error mt-4">{review.rejection_reason}</p>}{error && <p role="alert" className="notice-error mt-4">{error}</p>}
      {(review.kind === 'companies' || review.status === 'PENDING') && <div className="mt-6 border-t border-slate-100 pt-5">{review.kind === 'requests' && <label className="block text-sm font-medium">Rejection reason<textarea className="input mt-2" maxLength={500} value={reason} onChange={e => setReason(e.target.value)} placeholder="Explain what needs to be corrected before resubmission." /></label>}<div className="mt-4 flex flex-wrap justify-end gap-2"><button className="btn-secondary" disabled={busy} onClick={() => setReview(null)}>Cancel</button><button className="btn-danger" disabled={busy || (review.kind === 'requests' && !reason.trim())} onClick={() => mutate(review.kind === 'companies' ? `/admin/companies/${review.id}/status` : `/admin/card-requests/${review.id}/decision`, review.kind === 'companies' ? { status: 'REJECTED' } : { decision: 'REJECTED', reason: reason.trim() })}>Reject</button>{review.kind === 'companies' && review.status === 'APPROVED' ? <button className="btn-danger" disabled={busy} onClick={() => mutate(`/admin/companies/${review.id}/status`, { status: 'SUSPENDED' })}>Suspend company</button> : <button className="btn-primary" disabled={busy} onClick={() => mutate(review.kind === 'companies' ? `/admin/companies/${review.id}/status` : `/admin/card-requests/${review.id}/decision`, review.kind === 'companies' ? { status: 'APPROVED' } : { decision: 'APPROVED' })}>{busy ? 'Saving decision…' : review.kind === 'companies' ? 'Approve company' : 'Approve & generate cards'}</button>}</div></div>}
    </ReviewDialog>}
  </>;
}
