import assert from 'node:assert/strict';
import fs from 'node:fs';
const validation = 'data:text/javascript;base64,' + Buffer.from(fs.readFileSync(new URL('../lib/validation.js', import.meta.url),'utf8')).toString('base64');
const source = fs.readFileSync(new URL('../lib/csv.js', import.meta.url),'utf8').replace("'./validation'", JSON.stringify(validation));
const { parseEmployeeCsv } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
const header='employee_id,name,designation,department,email,phone\n';
assert.equal(parseEmployeeCsv(header+'E1,"Doe, Jane",Engineer,R&D,jane@example.com,+8801')[0].values.name,'Doe, Jane');
assert.equal(parseEmployeeCsv(header+'E1,Jane,Engineer,R&D,jane@example.com,+8801\nE1,John,Engineer,R&D,john@example.com,+8802')[1].errors.length,1);
assert.equal(parseEmployeeCsv(header+'E1,Jane,Engineer,R&D,jane@example.com,+8801',['E1'])[0].errors.length,1);
assert.ok(parseEmployeeCsv(header+'E1,Jane,Engineer,R&D,invalid,+8801')[0].errors.length);
assert.throws(()=>parseEmployeeCsv('name\nJane'),/Missing columns/);
assert.throws(()=>parseEmployeeCsv(header+'E1,"Jane'),/closing quote/);
assert.equal(parseEmployeeCsv(header+'E1,"Jane\nDoe",Engineer,R&D,jane@example.com,+8801')[0].values.name,'Jane\nDoe');
console.log('CSV functional checks: 7 passed');
